config/routes.rb
FortFolly::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :people

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/feed',    to: 'static_pages#feed'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :user_id, :name, :sex, :band_member, :registry_number, :father_id, :mother_id, :date_of_birth, :date_of_death, :place_of_birth, :place_of_death, :place_of_burial, :notes, :photo
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
      :default_url => "/assets/NoPhotoAvailable.jpg"
  belongs_to :user
  belongs_to :father, :class_name => 'Person'
  belongs_to :mother, :class_name => 'Person'
  has_many :children_of_father, :class_name => 'Person', :foreign_key => 'father_id'
  has_many :children_of_mother, :class_name => 'Person', :foreign_key => 'mother_id'

  scope :children_for, lambda {|father_id, mother_id| where('father_id = ? AND mother_id = ?', father_id, mother_id) }

  validates :name, presence: true, length: { maximum: 255 }

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      flash[:success] = "Person created successfully."
      redirect_to @person
    else
      render 'new'
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      flash[:success] = "Person updated"
      redirect_to @person
    else
      render 'edit'
    end
  end

  def index
    @people = Person.paginate(page: params[:page])
  end

  def destroy
    Person.find(params[:id]).destroy
    flash[:success] = "Person destroyed."
    redirect_to people_url
  end
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/people/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :user_id %>
<%= f.select :user_id, "<option>Nothing selected</option>" + options_from_collection_for_select(User.all, "id", "name", @person.user_id) %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :sex %>
<%= f.select :sex, options_for_select(["na", "male", "female"], @person.sex) %>

<%= f.label :band_member %>
<%= f.select :band_member, options_for_select([false,true], @person.band_member) %>

<%= f.label :registry_number %>
<%= f.number_field :registry_number %>

<%= f.label :father_id %>
<%= f.select :father_id, "<option>Nothing selected</option><option>Add new</option>" + options_from_collection_for_select(Person.all, "id", "name", @person.father_id) %>

<%= f.label :mother_id %>
<%= f.select :mother_id, "<option>Nothing selected</option><option>Add new</option>" + options_from_collection_for_select(Person.all, "id", "name", @person.mother_id) %>

<%= f.label :date_of_birth %>
<%= f.text_field :date_of_birth %>

<%= f.label :date_of_death %>
<%= f.text_field :date_of_death %>

<%= f.label :place_of_birth %>
<%= f.text_field :place_of_birth %>

<%= f.label :place_of_death %>
<%= f.text_field :place_of_death %>

<%= f.label :place_of_burial %>
<%= f.text_field :place_of_burial %>

<%= f.label :notes %>
<%= f.text_area :notes %>

<%= f.label :photo, "Upload Photo"%>
<%= f.file_field :photo %>
<br />

app/views/people/_person.html.erb
<li>
  <div class="container">
    <div class="row">
    <div class="span2">
      <% if !person.photo.url or person.photo.url.blank?%>
        <%= image_tag "/assets/NoPhotoAvailable.jpg", alt: "No Image Available" %>
      <% else %>
        <%= image_tag person.photo.url, alt: person.name + " Image" %>
      <% end %>
    </div>
    <div class="span9">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Sex</th>
            <th>Father</th>
            <th>Mother</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= person.name %></td>
            <td><%= person.sex %></td>
            <td><%= person.father.name if person.father && person.father != 0 %></td>
            <td><%= person.mother.name if person.mother && person.mother != 0 %></td>
          </tr>
        </tbody>
        </table>

      <table class="table">
        <thead>
          <tr>
            <th>Date of birth</th>
            <th>Place of birth</th>
            <th>Date of death</th>
            <th>Place of death</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= person.date_of_birth %></td>
            <td><%= person.place_of_birth %></td>
            <td><%= person.date_of_death %></td>
            <td><%= person.place_of_death %></td>
          </tr>
        </tbody>
        </table>

        <%= link_to "show", person %>
        <% if current_user.admin? %>
          | <%= link_to "edit", edit_person_path(person.id) %>
          | <%= link_to "delete", person, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/people/edit.html.erb
<% provide(:title, "Edit person") %>
<h1>Update person profile</h1>
<div class="row">
  <div class="span3">
    <% if @person.photo.url %>
      <%= image_tag @person.photo.url , alt: @person.name + " Image" %>
    <% end %>
  </div>

  <div class="span6">
    <%= form_for(@person) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/people/index.html.erb
<% provide(:title, 'All people') %>
<h1>All people</h1>

<%= will_paginate %>

<% @people.each do |person| %>
<ul class="users">
   <%= render person %>
</ul>
<% end %>

<%= link_to "Add new person", new_person_path %>

<%= will_paginate %>

app/views/people/new.html.erb
<% provide(:title, 'New Person') %>
<h1>New Person</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@person) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create person", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/people/show.html.erb
<% provide(:title, @person.name) %>
<h1>Profile Page</h1>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <% if !@person.photo.url or @person.photo.url.blank?%>
          <%= image_tag "/assets/NoPhotoAvailable.jpg", alt: "No Image Available" %>
        <% else %>
          <%= image_tag @person.photo.url , alt: @person.name + " Image" %>
        <% end %>
        <p><%= @person.name %></p>
      </h1>
    </section>
  </aside>
  <div class="span7">
    <p>User ID: <%= @person.user_id %></p>
    <p>Name: <%= @person.name %></p>
    <p>Sex: <%= @person.sex %></p>
    <p>Band Member: <%= @person.band_member %></p>
    <p>Registry Number: <%= @person.registry_number %></p>
    <p>Father Name: <%= @person.father.name  if @person.father && @person.father != 0%></p>
    <p>Mother Name: <%= @person.mother.name  if @person.mother && @person.mother != 0%></p>
    <p>Date of Birth: <%= @person.date_of_birth %></p>
    <p>Date of Death: <%= @person.date_of_death %></p>
    <p>Place of Birth: <%= @person.place_of_birth %></p>
    <p>Place of Death: <%= @person.place_of_death %></p>
    <p>Place of Burial: <%= @person.place_of_burial %></p>
    <p>Notes: <%= @person.notes %></p>
  <p><%= link_to "Back to index", people_path %> | <%= link_to "Add new person", new_person_path %>
  </p>
  </div>
</div>