config/routes.rb
FortFolly::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :people

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/feed',    to: 'static_pages#feed'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= page_entries_info @feed_items %>
  <%= will_paginate @feed_items, page_links: page_links %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= wrap feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_home.html.erb
<div class="center hero-unit">
  <div class="row">
    <div class="span2">
      <img src="/assets/flag.jpg" alt="Mi'kmaq Flag" width="150" height="100">
    </div>
    <% if signed_in? %>
    <div class="span3">
    <% else %>
    <div class="span6">
    <% end %>
      <img src="/assets/fffnsign.png" alt="Reserve Logo" width="200" height="200">
    </div>
    <div class="span2">
      <img src="/assets/pipe.jpg" alt="Pipe Image" width="133" height="100">
    </div>
  </div>
  <div class="row">
    <h1>Fort Folly First Nation</h1>
    <h2>Welcome to our page. Enjoy your stay.</h2>
  </div>
</div>
<div class="main-body">
  <div class="float-right">
    <img src="/assets/westmorland.jpg" alt="Westmorland Map" width="250" height="177">
  </div>
  <p>The Fort Folly First Nation Band is located in Dorchester, NB, about 13kms west of Sackville, NB, and about 40kms east of Moncton, NB.</p>

  <p>The community resides on approximately 40 hectares of land.</p>

  <p>Fort Folly First Nation has a registered population of 106.</p>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, rows: "4", placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <% if current_user.use_gravatar %>
    <%= gravatar_for current_user, size: 52  %>
  <% elsif !current_user.avatar.blank? %>
    <%= image_tag current_user.avatar.url, alt: "User Image", width: 52, height: 52 %>
  <% else %>
    <%= image_tag "/assets/NoPhotoAvailable.jpg", alt: "No Image Available", width: 52, height: 52 %>
  <% end %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<div>
  <%= link_to "view my profile", current_user %>
</div>
<div>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</div>